apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibonacci-backend
  template:
    metadata:
      labels:
        app: fibonacci-backend
    spec:
      containers:
      - name: fibonacci-backend
        image: sylvienscotland/newfibonacci-backend:v1
        ports:
        - containerPort: 8080
