apiVersion: v1
kind: Service
metadata:
  name: fibonacci-frontend-service
spec:
  selector:
    app: fibonacci-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
