apiVersion: v1
kind: ConfigMap
metadata:
  name: fibonacci-frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Fibonacci Calculator</title>
    </head>
    <body>
    <h1>Fibonacci Calculator</h1>
    <form id="fibonacci-form">
        <label for="n">Enter a number:</label>
        <input type="number" id="n" required>
        <button type="submit">Calculate</button>
    </form>
    <div id="result"></div>
    
    <script>
        document.getElementById('fibonacci-form').addEventListener('submit', async (event) => {
            event.preventDefault();
            const n = document.getElementById('n').value;

            try {
                const apiUrl = `http://192.168.49.2:30925/api/fibonacci?n=${n}`;
                console.log(`Sending request to API: ${apiUrl}`);
                const response = await fetch(apiUrl);

                if (!response.ok) {
                    console.error(`API error: ${response.status}`);
                    document.getElementById('result').innerText = `Error: ${response.statusText}`;
                    return;
                }

                const result = await response.text();
                console.log(`Received response: ${result}`);
                document.getElementById('result').innerText = `Result: ${result}`;
            } catch (error) {
                console.error(`Fetch error: ${error.message}`);
                document.getElementById('result').innerText = `Error: ${error.message}`;
            }
        });
    </script>
    </body>
    </html>
